INSERT INTO article (title, content) VALUES
('Welcome to Our Website','This is the first post on our new website. Stay tuned for more updates!'),
('Top 5 Tips for Productivity', 'Discover the top 5 tips to boost your productivity and manage your time better.'),
('Healthy Eating Habits','Learn about healthy eating habits and how to incorporate them into your daily life.'),
('Upcoming Events in 2024','Check out our list of exciting events happening in 2024!'),
('Guide to Learning SQL','Start your journey to becoming proficient in SQL with this comprehensive guide.'),
('최신 테크 트렌드 2024','AI, 블록체인, 메타버스 등 2024년 주목해야 할 기술 트렌드를 소개합니다.'),
('여행지 추천: 숨은 명소','관광객이 잘 모르는 국내 숨은 여행 명소를 소개합니다.'),
('재테크 초보자 가이드','주식, 펀드, 적금 등 재테크 초보자를 위한 기본 개념을 설명합니다.'),
('홈트레이닝 루틴','집에서 할 수 있는 효과적인 운동 루틴과 꿀팁을 공유합니다.'),
('친환경 생활 실천법','일상에서 실천할 수 있는 환경 보호 방법을 알아봅니다.'),
('Python Programming Tips','Essential Python programming tips and best practices for beginners.'),
('Digital Marketing Strategy','Comprehensive guide to building an effective digital marketing strategy.'),
('Mental Health Awareness','Understanding the importance of mental health and self-care practices.'),
('Remote Work Success','Tips and tools for successful remote work and virtual collaboration.'),
('Gardening for Beginners','Basic gardening tips and tricks for starting your own home garden.'),
('Creative Writing Workshop','Improve your creative writing skills with these practical exercises.'),
('DIY Home Projects','Simple and affordable DIY projects to improve your living space.'),
('Sustainable Fashion','Guide to sustainable fashion choices and ethical shopping practices.'),
('Meditation Basics','Introduction to meditation and mindfulness practices for beginners.'),
('Financial Planning 101','Essential financial planning tips for long-term security.'),
('Web Development Trends','Latest trends and technologies in web development for 2024.'),
('Cooking on a Budget','Tips for preparing delicious meals while saving money.'),
('Photography Basics','Understanding camera settings and composition for better photos.'),
('Career Development','Strategies for career growth and professional development.'),
('Art of Public Speaking','Improve your public speaking skills with these proven techniques.'),
('반려동물 케어 가이드', '강아지와 고양이를 위한 기본적인 건강관리 방법을 알아봅니다.'),
('스마트홈 구축하기', '우리 집을 스마트하게 만드는 기기들과 설정 방법을 소개합니다.'),
('제로웨이스트 생활', '일회용품 없이 생활하는 방법과 대체품을 소개합니다.'),
('인테리어 트렌드', '2024년 주목받는 인테리어 스타일과 적용 방법을 알아봅니다.'),
('건강한 아침 식단', '영양가 있는 아침 식사 레시피와 준비 팁을 공유합니다.'),
('Cloud Computing Basics', 'Introduction to cloud computing and its fundamental concepts.'),
('Effective Time Management', 'Strategies for better time management and productivity.'),
('Social Media Marketing', 'Tips for building a strong social media presence.'),
('Cybersecurity Tips', 'Essential cybersecurity practices for personal and business use.'),
('Mobile App Development', 'Getting started with mobile app development basics.'),
('데이터 분석 입문', '데이터 분석의 기초와 필요한 도구들을 설명합니다.'),
('직장인 건강관리', '바쁜 직장인을 위한 건강관리 방법을 소개합니다.'),
('음악 감상 가이드', '클래식 음악 입문자를 위한 기초 가이드입니다.'),
('디지털 디톡스', '디지털 기기 사용을 줄이고 균형 잡힌 생활을 하는 방법.'),
('캠핑 초보자 가이드', '캠핑을 시작하는 분들을 위한 기본 장비와 팁 소개.'),
('Blockchain Technology', 'Understanding the basics of blockchain and cryptocurrency.'),
('Content Creation Tips', 'Guide to creating engaging content for various platforms.'),
('Machine Learning Basics', 'Introduction to machine learning concepts and applications.'),
('Urban Gardening', 'Tips for growing plants in limited urban spaces.'),
('Personal Branding', 'Building and maintaining your personal brand online.'),
('친환경 에너지', '재생 에너지와 에너지 절약 방법에 대해 알아봅니다.'),
('독서법 개선하기', '더 효과적인 독서를 위한 방법과 습관을 소개합니다.'),
('홈카페 만들기', '집에서 카페처럼 맛있는 음료를 만드는 방법.'),
('Network Security', 'Essential network security practices and protocols.'),
('Business Analytics', 'Introduction to business analytics and data-driven decision making.');

INSERT INTO member (email, password) VALUES
('john.doe@email.com', 'password123'),
('emma.smith@email.com', 'securePass456'),
('alex.wilson@email.com', 'userPass789'),
('sarah.kim@email.com', 'safePass321'),
('mike.brown@email.com', 'brownPass567'),
('lisa.park@email.com', 'parkPass890'),
('david.lee@email.com', 'leePass234'),
('amy.chen@email.com', 'chenPass567'),
('peter.wang@email.com', 'wangPass890'),
('susan.garcia@email.com', 'garciaPass123'),
('james.miller@email.com', 'millerPass456'),
('mary.taylor@email.com', 'taylorPass789'),
('robert.anderson@email.com', 'andersonPass012'),
('jennifer.thomas@email.com', 'thomasPass345'),
('william.martinez@email.com', 'martinezPass678'),
('elizabeth.robinson@email.com', 'robinsonPass901'),
('michael.white@email.com', 'whitePass234'),
('patricia.lewis@email.com', 'lewisPass567'),
('richard.moore@email.com', 'moorePass890'),
('barbara.hall@email.com', 'hallPass123')